name: Deploy to development

on:
  push:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build_and_deploy:
    needs: tests

    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: dev
      cloud_run_service: nettopp-mnemona-dev
      gar_repo_name: nettopp-mnemona
      gcp_project_id: nettopp
      gcp_region: europe-west1
    secrets: inherit
