name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build_and_deploy:
    needs: tests

    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: prod
      cloud_run_service: nettopp-mnemona
      gar_repo_name: nettopp-mnemona
      gcp_project_id: nettopp
      gcp_region: europe-west1
    secrets: inherit
